### ISSUE TITLE
Request to be a reviewer/contributor

### ISSUE THREAD

**Issue by MichelML** [conda-forge/django-rdkit-feedstock#2]
@roukydesbois can you add me as a contributor to this feedstock please? I made a patch of the package today and I need it to be release asap in conda-forge

thanks in advance :+1: 

my gh name is @MichelML

**Comment by roukydesbois** [comment]
Hello @MichelML and thanks for your interest in the feedstock! Can't you open a pull request to start with? I should be quite quick to look at it!

**Comment by MichelML** [comment]
True, thanks for the quick reply. Once the pypi package is released, maybe you can add me then? Might not even be necessary but just in case for next releases.

Thanks Thom

**Comment by MichelML** [comment]
nvm I remember there's no pypi package, but once my PR is merged I'll let you know

**Comment by roukydesbois** [comment]
Indeed, I should be notified when there is a new version of the package and I'll bump the version here too!

**Comment by rvianello** [comment]
Hi @roukydesbois fyi I just merged @MichelML 's PR and tagged the new revision.

btw, thank you for this feedstock.

**Comment by roukydesbois** [comment]
Alright, the bot was faster than me to prep everything to update the version, you should be good now @MichelML !

In the meantime, I'll look if and how I can add you to the repo.

**Comment by MichelML** [comment]
thanks guys, we shouldn't have to change it for a while, so I guess it's fine if you remain the only maintainer of the feedstock @roukydesbois 

thanks again!
